apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: gal-app
    appstudio.openshift.io/component: devfile-sample-go-basic-gal
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-go-basic-gal
  namespace: gbenhaim-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_redhat-appstudio_gbenhaim-test-repo
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/redhat-appstudio/gbenhaim-test-repo
